### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by tyler7771** [oscarmorrison/nightmare-heroku#6]
Having a weird syntax error that I can't figure out. Any help would be great!
This is my Heroku Logs. No idea where this error could be coming from so if you need to see other files I'm happy to provide them.

```
2017-08-24T22:11:42.361900+00:00 heroku[worker.1]: Starting process with command `DEBUG=* xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" node --harmony .meteor/heroku_build/bin/node $NODEJS_PARAMS .meteor/heroku_build/app/main.js`
2017-08-24T22:11:43.097597+00:00 heroku[worker.1]: State changed from starting to up
2017-08-24T22:11:48.404983+00:00 heroku[worker.1]: Process exited with status 1
2017-08-24T22:11:48.229718+00:00 app[worker.1]: /app/.meteor/heroku_build/bin/node:1
2017-08-24T22:11:48.229746+00:00 app[worker.1]: (function (exports, require, module, __filename, __dirname) { ELF
2017-08-24T22:11:48.229755+00:00 app[worker.1]:                                                               ^
2017-08-24T22:11:48.229763+00:00 app[worker.1]: 
2017-08-24T22:11:48.229764+00:00 app[worker.1]: SyntaxError: Unexpected token ILLEGAL
2017-08-24T22:11:48.229765+00:00 app[worker.1]:     at exports.runInThisContext (vm.js:53:16)
2017-08-24T22:11:48.229765+00:00 app[worker.1]:     at Module._compile (module.js:373:25)
2017-08-24T22:11:48.229766+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:416:10)
2017-08-24T22:11:48.229767+00:00 app[worker.1]:     at Module.load (module.js:343:32)
2017-08-24T22:11:48.229768+00:00 app[worker.1]:     at Function.Module._load (module.js:300:12)
2017-08-24T22:11:48.229768+00:00 app[worker.1]:     at Function.Module.runMain (module.js:441:10)
2017-08-24T22:11:48.229769+00:00 app[worker.1]:     at startup (node.js:140:18)
2017-08-24T22:11:48.229770+00:00 app[worker.1]:     at node.js:1043:3
2017-08-24T22:11:48.439650+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by oscarmorrison** [comment]
Hey @tyler7771 did you work this out? Looks like you got an error with a token in your main js file. Can you run this locally?
